package com.maligai.app.localization

enum class StringKey {
  Close, Cancel, Save, Delete, Next, Continue, Verify, Add, Edit, Reset, Done, Print, Update, Unlock, Menu,
  EnterAdminPin, Pin4Digit, Pin4DigitAdmin, ConfirmPin, ForgotPin, PinRecovery, Answer, AnswerLowercase,
  SecurityQuestion, WrongPin, WrongAnswer, PinMust4Digits, PinsDoNotMatch, EnterSecurityAnswer,
  SetUpMaligai, ChooseAppLanguage, ChooseAppLanguageHint, ChooseShopLanguage, ChooseShopLanguageHint,
  DownloadHandwritingPacks, DownloadHandwritingHint, English, Downloading, BothPacksReady, DownloadNow,
  FinishingSetup, StartingMaligai, Loading, UnlockBiometricTitle, UnlockBiometricSubtitle, SkipDownloadLater,
  Downloaded, DownloadingPhase,
  SecQ_MaidenName, SecQ_BestFriend, SecQ_FavoriteSport, SecQ_BornCity, SecQ_PetName,
  NewBill, TodaysBills, ShopSpending, Admin, Items, Ledger, Loans, Spending, Analysis, CsvBackup,
  GstReceipt, Printer, Settings, About,
  TodayBillsRevenue, CouldNotOpenBill, ReceiptPrinted, PrintResult,
  BluetoothNotAvailable, PrinterConnected, PrinterConnectionFailed, PrinterNotConnected, PrinterPrinted, PrinterPrintFailed,
  ClearBill, ClearBillConfirm, RemoveAllItems, AddItem, ItemName, Recognize, UnitType, ClearCanvas,
  SaveItem, BillPreview, SearchItems, SearchItemsPlaceholder, BrowseAllItems, PriceChanged,
  UpdateCatalogAndAdd, AddAtAmountOnly, EditLine, Item, Amount, CustomTotal, CustomQuantity, Quantity,
  TotalAmount, NewItem, Editable, SaveKadan, SaveAndPrint, KadanTitle, CustomerName, PhoneOptional,
  Recognizing, RefreshSuggestions, ResetBillNumber, Remove, UndoStroke, SaveCatalogChanges,
  PricePerUnit, UnitLabel, AddWithAmount, PricePerUnitFormatted,
  TapLoanToViewItems, BillNoLongerAvailable, NoItemsForLoan, OutstandingSlash, BillTotalLabel,
  LoanLeft, SubtotalCgstSgst, TotalLabel, KadanSuffix, BillNameKadan,
  AddItemBtn, SearchItemsLabel, SearchPlaceholder, NoItemsYet, NoMatchesFor, DeleteItemTitle,
  DeleteItemConfirm, AddItemTitle, EditItemTitle, Available,
  Orders, Revenue, Outstanding, Customers, NoOutstandingKadan, RecordPayment, LoansLabel, PaymentsLabel,
  PaymentAmount, LoanRow,
  AddSpend, Spent, Entries, EditSpend, ItemReason,
  Net, ItemsSold, NoSalesInPeriod,
  CsvBackupTitle, CsvAutoExport, InternalStorage, ExternalStorage, ExportNow, ImportLabel, ImportReplaceHint,
  ImportItems, ImportSpending, ReplaceDataTitle, ReplaceDataWarning, ExportedSuccess, ExportFailed,
  StorageOk, StorageNotWritable, StorageChecking,
  AppSection, RequireUnlock, RequireUnlockHint, Theme, System, Light, Dark,
  AppLanguage, ChangeAppLanguage, CurrentValue, HandwritingLanguage, ChangeHandwritingLanguage,
  HandwritingSwitchWarning,
  Gst, EnableGst, GstPercent, CustomCgstSgstSplit, CgstPercent, SgstPercent, PaperSpacing,
  ReceiptItemNames, FooterText, HeaderFields, AddHeaderField, LabelShopName, Value, ReceiptPreview,
  SaveSettings, LocalScriptReceipt, EnglishReceiptNames,
  SavedPrinter, ScanPairedDevices, PaperWidth, RupeeSymbolFix, ForgetPrinter, PaperWidthMm,
  PeriodToday, PeriodWeek, PeriodMonth, PeriodAll,
  UnitWeight, UnitVolume, UnitPiece, UnitKg, UnitLitre,
  Maligai, IndiaHandwritingPos, VersionLabel, OfflineFirst, RecentSpending,
  AddSpendTitle, AddHeaderFieldTitle,
  EnglishPackFailed, RegionalPackFailed, CouldNotDownloadEnglish, CouldNotDownloadRegional,
  ReceiptBill, ReceiptDate, ReceiptSubtotal, ReceiptCgst, ReceiptSgst, ReceiptTotal,
  Increase, Decrease, Up, Down,
  ConfirmLabel,
  Hidden, DotsAboveHeader, DotsBelowFooter, LocalScriptReceiptHint, ReceiptPreviewHeader,
  Connected, NotConnected, NoPairedBluetooth, DataLowercase,
  HandwritingPacksNotReadyShopLanguage, HandwritingPacksNotReadySetup, Total, Kadan, Preview,
  AddItemsFirst, ItemAddedToBill, SavedAsKadanFor, SavedPrintResult, BillCompletedPrinted, BillCompleted,
  ItemSavedToCatalog, AddAsNewItem, AllItems, NoItemsInCatalogAdmin,
  CatalogPriceFormula, YouWroteAmount, DefaultPriceUnit, PriceLabel, EnterCustomTotalOverride,
  CouldNotSaveItem, CouldNotUpdateItem, FillThenSaveHint, ItemSavedThenUpdateHint,
  TotalAmountWithoutQuantity, LineTotal,
  CustomQtyHintWeight, CustomQtyHintVolume, CustomQtyHintCount,
  SelectedQuantity, InvalidFormatHint,
  PackNotDownloaded, HandwritingPackStatusFor
}
